global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'scrapper'
    static_configs:
      - targets: ['localhost:8080']
