scrape_configs:
  - job_name: 'node'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s

    static_configs:
      - targets: ['localhost:8080']
        labels:
          group: 'scrapper'

      - targets: ['localhost:8081']
        labels:
          group: 'bot'
