CREATE TABLE dbo.links (id INTEGER PRIMARY KEY, link NVARCHAR(128) NOT NULL);

CREATE TABLE Links (id INTEGER PRIMARY KEY, tg_chat_id BIGINT NOT NULL);

CREATE TABLE links_tgChats (
FOREIGN KEY (LinkID) REFERENCES links (id),
FOREIGN KEY (ChatID) REFERENCES tgChats (id)
);