services:
  PostGreSQL:
    image: postgres:latest
    environment:
      POSTGRES_DB: "scrapper"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=admin
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend