name: Bot Build

on:
  push:
    paths:
      - 'FP/bot/**'

jobs:
  build:
    name: Build Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Bot Application
        run: mvn package -pl bot -am