name: Scrapper Build

on:
  push:
    paths:
      - 'FP/scrapper/**'
      - 'FP/pom.xml'
  pull_request:
    paths:
      - 'FP/scrapper/**'
      - '.github/workflows/scrapper.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: cd FP && mvn package -pl scrapper -am
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build scrapper Docker image
        run: cd FP && docker build -t scrapper-image -f scrapper.Dockerfile -t ray-not/javaguava/scrapper:latest .
        
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/ray-not/javaguava/scrapper:latest
