name: Scrapper Build

on:
  push:
    paths:
      - '.FP/scrapper/**'
  pull_request:
    paths:
      - '.FP/scrapper/**'
      - '.github/workflows/scrapper.yml' # Include this path to trigger the workflow when changes are made to the workflow file itself

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and package scrapper
        run: mvn package -pl scrapper -am
