name: Scrapper Build

on:
  push:
    paths:
      - 'FP/scrapper/**'
      - 'FP/pom.xml'
  pull_request:
    paths:
      - 'FP/scrapper/**'
      - '.github/workflows/scrapper.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: cd FP && mvn package -pl scrapper -am
